kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-encrypted
  annotations: 
    storageclass.kubernetes.io/is-default-class: "true"   # Make this storageClass as Default
provisioner: ebs.csi.aws.com   # Amazon EBS CSI driver
parameters:
  type: gp2
  encrypted: 'true'   # EBS volumes will always be encrypted by default
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
mountOptions:
- debug
